# Generated by Django 5.0.4 on 2024-05-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bannertagfeature',
            name='unique_banner',
        ),
        migrations.AddConstraint(
            model_name='bannertagfeature',
            constraint=models.UniqueConstraint(fields=('tag', 'feature'), name='unique_banner', violation_error_message='A banner must have a unique tag and feature'),
        ),
    ]
