# Generated by Django 5.0.4 on 2024-08-01 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbanner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbanner',
            name='user_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.tag', verbose_name='tag_id'),
        ),
        migrations.AddConstraint(
            model_name='bannertagfeature',
            constraint=models.UniqueConstraint(fields=('tag', 'feature'), name='unique_banner', violation_error_message='A banner must have a unique tag and feature'),
        ),
    ]
