# Generated by Django 5.0.4 on 2024-08-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_remove_bannertagfeature_unique_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbanner',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userbanner',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userbanner',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='userbanner',
            name='id',
            field=models.BigAutoField(auto_created=True, default=False, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
